# Generated by Django 6.0.3 on 2026-03-04 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'Nouveau'), ('progress', 'En cours'), ('won', 'Gagné'), ('lost', 'Perdu')], default='new', max_length=20)),
                ('source', models.CharField(blank=True, max_length=120)),
                ('value_estimate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
